src/Legacy/Pdf.php
Linha 826:
de:
$this->detLineWidth($w);
para:
$this->setLineWidth($w);
=> Correção de Método

examples/testaDacceCTe.php, src/CTe/Dacce.php
Classe para impressão de Carta de Correção CT-e e arquivo de exemplo.
=> Inclusão de Classe carta de correção para CTe

src/CTe/Dacte.php
Ajustei o bloco Documentos Originários para já na página 1 mostrar até 16 NF-e ( ou outro doc ) se o xml conter mais que isso irá gerar a pagina 2 contendo o restante( nesse caso só implementei NF-e, mas fique a vontade para fazer com o demais doc )
=> DOCUMENTOS ORIGINÁRIOS - Continuação ( pagina 2 )

src/CTe/Dacte.php
- Adicionado os CT-es anteriores na impressão da DACTE, no campo de Documentos Originários.
- Adicionado possibilidade de colocar nome e site da empresa na impressão da DACTE
=> Adição de campos na DACTE

src/CTe/Dacte.php
- Ajustado impressão da CT-e quando CT-e é de anulação.
=> - Ajustado impressão da CT-e quando CT-e é de anulação.

src/MDFe/Damdfe.php
- Ajustado para impressão da MDF-e que não estava funcional.
=> - Ajustado impressão de MDF-e

src/MDFe/Damdfe.php
=> [FIX] Mudança no import e esqueceu de mudar na classe

src/CTe/DacteOSV3.php
Foi adicionado novo arquivo para impressão da CT-e de Outros Serviços (modelo 67)
=> Inclusão do documento auxiliar para CT-e OS

src/NFe/Danfe.php
=> Danfe emitido por PF

src/MDFe/Damdfe.php
=> Adicionando verificação de campo infCpl

src/CTe/Dacce.php
- Adicionada função render() para geração do PDF.
- Adicionado possibilidade do desenvolvedor colocar o nome dele no rodapé da impressão da DACCE.
=> Ajustes DACCE

src/NFe/Danfce.php
Adiciona informações opcionais no fim do PDF, tag "infAdic". Commit atualizado e refeito.
=> Adiciona informações opcionais na NFCe

src/CTe/DacteV3.php
- Adicionado impressão de CT-e para modal Aéreo;
- Ajustado espaçamento e encerramento de alguns groupboxes que estavam maiores que o necessário;
- Ajustado referente a busca de informações quando CST de ICMS é de Outros porém de Outra UF que possui campos específicos para os impostos;
- Ajustado quantidade de CT-es vinculados em uma folha;
=> Adicionado Modal Aéreo

src/Legacy/Common.php, src/NFe/Danfce.php, src/NFe/Danfe.php
A variável hInfAdic não estava inicializada e isso gerava um erro, inicializei com zero pois o campo não é usado no método pInfAdic()
=> Inicialização variável, novos fretes e tipos de pagamento

src/NFe/Danfce.php
Texto informativo ao tentar imprimir a danfe com NFC-e cancelada ou denegada.
=>  NFC-e cancelada ou denegada

src/NFe/Danfce.php
Centralizei o QRCode na Impressão da Danfe da NFC-e.
=> Ajuste na posição do QRCode da NFC-e.

src/NFe/Danfe.php
Ajuste para impressão de imagem do logo em PNG com ou sem Alpha Channel e permitir o envio de imagem em string
=> Imagem do LOGO

src/NFe/Danfe.php
Alterações para permitir a impressão no DANF dos dados contidos na tag veicProd.
=> Possibilidade Imprimir os dados contidos na tag veicProd do item

src/NFe/Danfe.php
Execução do método pFaturaDANFE caso tenha  
$this->dup->length > 0
=> Impressão de fatura caso tenha duplicata

src/NFe/Daevento.php
removido parâmetro "situacao_externa" da função "montaDaEventoNFe"
=> Remoção de parâmetro incorreto

src/NFe/Danfe.php
Estava dando esse erro para gerar em landscape Undefined variable: nInicio, vendor/nfephp-org/sped-da/src/NFe/Danfe.php, 2723
=> variavel  nao existe

src/MDFe/Damdfe.php
Este pr é uma versão mais aproximada do proposto pelo manual "[aqui](https://dfe-portal.svrs.rs.gov.br/MDFE/DownloadArquivoEstatico/?sistema=MDFE&tipoArquivo=1&nomeArquivo=MOC_MDFe_Anexo%20II_DAMDFE_v3.00a.pdf)" do portal MDF-e (pág. 11)
As mudanças podem ser vistas neste [link](https://filebin.net/mhwlk8ajytc646pj)
=> [UPD] Melhorias no layout do Damdfe

src/NFe/Danfe.php
Segue XML com o erro: 
[mod55-nfe.xml.zip](https://github.com/nfephp-org/sped-da/files/2619404/mod55-nfe.xml.zip)
[Notas Fiscais.pdf](https://github.com/nfephp-org/sped-da/files/2619411/Notas.Fiscais.pdf)
[testaDanfe.php.pdf](https://github.com/nfephp-org/sped-da/files/2619421/testaDanfe.php.pdf)
=> Correcao de bug em casos que deveria ter a segunda pagina de itens, mas acabava duplicando

src/NFe/Danfe.php
Incluir tags do icmsRet na impressão da nfe
=> Inclusão tag icmsRet no pdf

src/CTe/DacteOSV3.php
Fiz atualização na classe para impressão de CTeos
=> Atualização da classe para qrCode CTeos

src/CTe/DacteV3.php, src/NFe/Danfe.php
Estou processando algumas CTe's e houve erro ao emitir a Dacte, arquivo nfephp-org/sped-da/src/CTe/DacteV3.php.
Solicito gentileza de alteração da linha 2163 (Método zGeraChaveAdicCont):
de:
`$dd = $this->ide->getElementsByTagName('dEmi')->item(0)->nodeValue;`
para:
`$dd = $this->ide->getElementsByTagName('dhEmi')->item(0)->nodeValue;`
=> -- ajuste na tag dhEmi

src/CTe/Dacanc.php, src/CTe/Dacce.php, src/CTe/Dacte.php, src/CTe/DacteOS.php, src/CTe/Daevento.php, src/NFe/Daevento.php
devido a correção aplicada pelo roberto na classe de MDFe, notei o mesmo em todas as outras. Essa correção aplica tudo removendo por completo o método inexistente convertTime do projeto
=> aplicando correção do mdfe para todas as classes

examples/cte/dacce.php, src/CTe/Dacce.php
incluída a variável do logotipo e do retorno da função render()
=> ajuste no logotipo

src/NFe/Danfe.php
Adicionado grupos de locais de retirada e entrega conforme NT 2018.005
=> Adicionado grupos de locais de retirada e entrega

src/MDFe/Damdfe.php
Hoje imprime fixo o Peso Total (Kg), mas a medida pode ser KG ou Tonelada. Criado a condição para verificar quando tem que imprimir um ou outro.
=> Mostrar unidade Kg ou Ton

src/CTe/Dacte.php
=> Correção exibição das NF no DACTe

src/NFe/Danfe.php
Conforme falado na #308 , segue uma sugestão de correção.
Obrigado.
=> Caixa para cnpj

src/NFe/Danfe.php
Reverts nfephp-org/sped-da#318
=> Revert "Correção Danfe.php"

src/NFe/Danfe.php
Reverts nfephp-org/sped-da#319, Perdão nesse projeto só tem a branche master mesmo, então é feito o pr direto mesmo, obrigado pela contribuição.
=> Revert "Revert "Correção Danfe.php""

src/NFe/Danfce.php
Testa xMsg no infAdic para quando o XML não tem a tag
=> Testa xMsg no infAdic

src/NFe/Danfe.php
=> Inclusão VALOR DESC nos items do DANFe modelo 55

src/BPe/Dabpe.php
=> Criada versão BETA do DABPe tamanho reduzido

examples/nfe/danfe.php
Infome os novos metodos para utilização da classe
=> ajustes no exemplo

src/NFe/Danfe.php
Foram adicionados 3 novos configuradores.
1. Configurador para exibir dados da unidade de medida tributável;
2. Configurador para casas decimais de valor comercial;
=> Configuração também é aplicada aos campos das unidades de medida tributável;
3. Configurador para casas decimais de quantidade comercial;
=> Configuração também é aplicada aos campos das unidades de medida tributável;
```
$danfe->setVUnComCasasDec(2);
$danfe->setQComCasasDec(0);
$danfe->setMostrarUnidadeTributavel(true);
```
Alguns produtos que são vendidos em unidade, podem ser vendidos em CX, sendo a unidade tributável a UN, então, foi adicionado a exibição da unidade de medida tributável logo abaixo da unidade comercial.
Aproveitei também e adicionei configuradores para a quantidade de casas decimais, estavam fixadas em …
=> NF-e: Adicionado configurador para Unidade Tributável

src/BPe/Dabpe.php
O DABPE exibia apenas um percurso da TAG infViagem. Agora ajusta o tamanho da página e exibe múltiplos percursos, adicionando a palavra CONEXÃO quando o tpTrecho = 3 (Conexão);
=> Modificado para exibir as tags infViagem quando mais de uma informada.

src/CTe/Dacte.php
Correção da condição para chamar as funções que exibe as chaves de NFe e NF.
=> Correção de condição

src/NFe/Danfe.php
Exibe forma de pagamento 99=Outros
=> Exibe forma de pagamento 99=Outros

src/CTe/Dacte.php, src/MDFe/Damdfe.php
Corrigido mascara do DAMDFe no caso de emitente com IE com mais de 10 como é o caso de alguns emitentes em SP.
=> Corrigido mascara do DAMDFe no caso de emitente com IE com mais de 10 dig.

src/MDFe/Damdfe.php
Fix https://github.com/nfephp-org/sped-da/issues/383
Vales pedágios geravam erros e estavam com CNPJs invertidos.
=> Fix Vale Pedágios MDFe

src/NFe/Danfe.php
@robmachado 
Em referência ao #380 que acabei fechando sem querer ao fazer um rebase, segue a alteração conforme a pull-request anterior com o fonte atualizado.
=> Complemento: Unidade de Medida Tributável

src/CTe/Dacte.php, src/CTe/DacteOS.php
Criado leiaute para CTe Multimodal, e pequenas correções no DACTe e DACTeOS.
=> Criado Leaiute para CTe Multimodal e pequenas correções.

src/NFe/Danfe.php
Estava sendo impressa a posição Y no label do box de fatura
=> removido do label da fatura a posição Y

src/NFe/Traits/TraitBlocoVII.php
Ajuste para a impressão das dezenas quando existir.
=> Impressão das dezenas NOTA MS PREMIADA

src/NFe/Danfe.php
Segue correção para emissão da danfe sem o protocolo de autorização.
=> Geração da danfe sem o protocolo de autorização

src/NFe/Traits/TraitBlocoV.php
Novos meios de pagamento (NT2020.006) para cupom fiscal
=> pagType novos meios

src/Legacy/Common.php, src/NFe/Danfe.php
Nas impressões está saindo a data errada. Está saindo o valor UTC ao invés do timestamp do Brasil.
Aqui segue um exemplo, para mostrar que o valor está errado.
https://www.tehplayground.com/3VbeXLSe7WjRSAHU
=> Fix issue with timezone

examples/nfe/danfe.php
Instrução de uso do método setOcultarUnidadeTributavel
=> Instrução de uso do método

src/NFe/Traits/TraitBlocoI.php
Adicionei o telefone do Emitente no Danfce, no cabeçalho, após a Cidade-UF
=> Adiciona telefone do emitente no Danfce

src/CTe/Dacte.php
verificação se valor não está em branco antes de formata-lo como numérico.
=> Update Dacte.php : verificação se valor não está em branco antes de formata-lo como numérico.

src/NFe/Danfe.php
Inclusão do vICMSSubstituto na descrição do produto
=> Inclusão do vICMSSubstituto

src/NFe/Danfe.php
=> fix: validando datetime antes de usar

src/NFe/Danfce.php, src/NFe/Traits/TraitBlocoII.php, src/NFe/Traits/TraitBlocoVII.php
Correções no DANFCe em relação ao tpEmis = 9 (OFFLINE).
Na reimpressão, mesmo com protocolo, o DANFCe estava imprimindo 'Pendente Autorização'.
=> Ajustes DANFCe

src/NFe/Danfe.php
Atribui se será gerado informações adicionais automatica.
=> Inclusão da função setGerarInformacoesAutomaticas

src/CTe/Dacte.php
Correção afim de exibir de forma separada as unidades de medida do CT-e.
Mais informações listadas no issue [603](https://github.com/nfephp-org/sped-da/issues/603).
=> Correção para exibição individual das unidades med

src/CTe/DacteOS.php
Foi adicionado o campo ObsFisco para mostrar em USO EXCLUSIVO DO EMISSOR DO CT-E.
=> Update DacteOS.php mostrar as informacoes do Fisco

src/NFe/Danfe.php
Solicitação para incluir títulos nos PDFs.
[Issue 602](https://github.com/nfephp-org/sped-da/issues/602)
=> Inclusão de títulos no PDF
