src/CTe/Dacte.php

Caso o CTE esteja preenchido, porém ainda não autorizado o uso na SEFAZ(não transmitido), pode ser feito uma pré-visualização da impressão e o usuário verifica as informações antes de confirmar a transmissão, podendo fazer uma edição normal pois ainda não foi transmitido.

pré-visualizar impressão

---

src/CTe/Dacte.php

Ao utilizar a função para gerar a DACTE da versão 2.00, ocorre uma exception na função number_format.
Observei que na versão 3.00 o problema já foi corrigido e apliquei a mesma lógica na versão 2.00

Correcao do erro number_format na V2 com base na V3

---

src/CTe/DacteV3.php

- Atualização para classe Legacy (Common não contém mais classe Dom).
- Remoção tag **_locEnt_** descontinuada no leiaute 3.00 do CT-e.

Atualização Dacte

---

src/MDFe/Damdfe.php

Removendo feature do PHP 7 (Null coalescing) para manter compatibilidade com versoes do PHP (5.5 | 7.0)

#76 - removendo feature do PHP 7

---

src/CTe/DacteV3.php

[problema identificado]: 
- Texto campo situação tributária com valor diferente do esperado #79 
[correções]
- adicionado a relação de propriedade da classe DACTeV3 a propriedade ICMSSN que estava sendo criada dinâmicamente.
- adicionado propriedade ICMSOutraUF como propriedade de classe de modo a receber valor da respectiva tag.
- no método zImpostos, removido trecho de código que estava concatenando valor 1 a string situação tributária.
- no método zImpostos, adicionado validação ao criar texto situação tributária para quando CST for 90, de modo a atribuir valor conforme orientações do manual do contribuinte.

Aprimorado texto situação tributária para considerar também ICMSSN e ICMSOutraUF

---

src/CTe/DacteV3.php

1.  Caso o xml tenha sido gerado na versão 2.00 a tag tomador não estava sendo encontrada. Assim o tomador não era impresso na Dacte.
2. Identificação pelo código da unidade e não mais pela posição no xml, sendo que isso forçava a criação da tag xml na posição 0 para unidade de medida KG(Quilos)
3. Quantidade de NF-e na página inicial para completar bloco em branco. Havia uma limitação de 15 notas sendo que o bloco comporta até 26.

Melhorias na Dacte

---

src/NFe/Danfe.php

Ocorria que quando não houvesse conteúdo na tag indPag (na versão 4), o resultado de pSimpleGetValue era uma string vazia, entrando na validação de pagamento a vista.
Ajustado para utilizar o operador de comparação "identico", validando o tipo do resultado.

Ajustes na verificação de tipo de pagamento

---

src/NFe/Danfe.php

The function `printDANFE()` doesn't even exist. Copied from [`NFePHP\DA\NFe\Danfce::printDANFE()`](https://github.com/nfephp-org/sped-da/blob/master/src/NFe/Danfce.php#L829)

Fix print output pdf danfe

---

src/NFe/Danfce.php

Informei o valor do frete para aparecer no layout da DANFE;
No manual do contribuinte, vi que o vfrete pode ser incluído, portanto fiz as alterações para inclui-lo.
Também alguns ajustes para que o layout continuasse no padrão.

Inclusão do Valor do Frete no Layout da Danfce

---

src/NFe/Dacce.php
src/NFe/Danfce.php
src/NFe/Danfe.php

Atualizando a descrição do campo IVA para IVA/MVA na descrição do produto no layout da DANFE, o motivo é que o pessoal de testes da empresa que trabalho "reclamou" por que o termo IVA não é usado aqui no PR mas sim, MVA. 
Adicionando outras formas de pagamento que ainda não haviam sido adicionadas conforme a [NT_2016_002_v1.42](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=20k0jfiSgtk=)
Limpei a variável $texto antes de verificar se existe CNPJ ou CPF do destinatário, pois quando não encontrava nenhum dos dois, era inserido duas vezes o texto "De acordo com as determinações legais vigentes, vimos por meio desta comunicar-lhe.."

correções visuais na Danfe e Dacce

---

src/NFe/Danfe.php

Na versão 4.0 da NFe o lote foi removido do grupo Med e foi criado um grupo chamado Rastro.
Se não possuir o rastro mantem o que estava fazendo no 3.1 caso exista utilizará para adicionar as informações no lote na descrição do produto.

[UPD] Informações do lote Med -> Rastro

---

src/NFe/Danfe.php

Dependendo da versão do xml a tag tPag não está presente. 
pAnfavea era a única função private e não há necessidade.

verifica a existencia de tPag; muda de private para protected a função pAnfavea

---

composer.json
src/CTe/DacteV3.php

- Verifica se a tag vTotTrib nao esta vazia, o que ocasiona um erro na função number_format.
- Ajuste na impressão do campos CUBAGEM(M3) e QDTE(VOL).
- Inclusão dos campos de de ICMS ST na impressão dos impostos.

Ajustes vTotTrib, Campos CUBAGEM(M3), QTDE(VOL) e ICMS ST

---

src/NFe/Danfe.php

Adiciona os campos de FCP nas informações complementares do produto, como solicitado na página 75 da NT 2016.002

Campos de FCP nas informações complementares

---

src/NFe/Danfe.php

Na NF-e 4.00, há um totalizador para o valor do FCP da operação, desmembrado do total do ICMS.
O totalizador do FCP da DIFAL, sendo chamado de "Valor do FCP", é ambíguo. Mudei para "V. FCP UF Dest"
para que fique claro qual é o FCP tratado no campo.

Desambiguação no total do FCP da UF destino

---

src/NFe/Danfe.php

Alguns cliente solicitaram que fossem exibidas as formas de pagamento no DANFE.
Gerei essa nova função pagamentoDANFE, baseada na faturaDANFE. Usando o mesmo formato de impressão exibe a forma de pagamento e o valor.
Alterei para que fosse usada a pagamentoDANFE no lugar da faturaDANFE no caso de pagamentos que não sejam só boletos.
Talvez adicionar uma opção na criação da classe se é para exibir ou não o pagamento?
Caso o pagamento seja "90 - Sem Pagamento" ou "99 - Outros" não imprime nada.

Adição das formas de pagamento no DANFE - novo

---

src/NFe/Danfe.php

O box da nfe fica desalinhado com ```$w1 = 16; ``` com ```$w1 = 18;``` fica alinhado
```$w1 = 16; ``` 
```$w1 = 18; ```

[UPD] box numero alinhado

---

src/Legacy/Common.php

Como descrito na _ISSUE_ #186, os caracteres especiais — como o _ampersand_ (&) —  são codificados em caracteres _HTML_ validos para a geração do _XML_, mas não são decodificados para a impressão, causando problemas de visualização do PDF.
Esta correção adiciona o tratamento desses caracteres no texto que será inserido no _textBox_, os decodificando em caracteres _HUMAN-READABLE_.
> É necessário observar que na consulta da nota na _SEFAZ_ **a exibição é conforme o que está no XML**

[UPD] Decodifica os caracteres HTML na impressão (ISSUE #186)

---

src/NFe/Danfe.php

- Foi colocado um html_entity_decode no método "pDescriçãoProduto" na danfe do NFe, para que os caracteres html sejam convertidos na hora da impressão da nota.

Decodificação de caracteres html no campo descrição do produto

---

src/CTe/DacteOSV3.php
src/CTe/DacteV3.php
src/MDFe/Damdfe.php

Ajustado para que ao ser gerado o pdf de um CTe ou MDFe e o mesmo não possua a informação do QRCode no xml para que seja gerado a seguinte informação no QRCode: 'SEM INFORMAÇÃO DE QRCODE', com isso o layout não ira ficar desconfigurado.

SEM INFORMAÇÃO DE QRCODE

---

src/NFe/Danfe.php

Adicionando a leitura do detPag no loadDoc para ser utilizada na função pagamento.
Também foi alterado a forma que é calculado a quantidade de linhas das duplicatas. Como existe a possibilidade de não haver duplicatas e sim outras formas de pagamento, verificando o total das formas de pagamento.
A ideia é que ao imprimir as formas de pagamento são exibidas duas linhas (forma e valor), na exibição das duplicatas são 3 (num, vencimento e valor), para cada item.
Não alterei a função pagamento mas talvez seja necessário alterar ela para aumentar a altura de cada item para que fique igual, em altura, das duplicatas.

Adicionando a leitura do detPag loadDoc

---

src/NFe/Danfce.php

Bom dia,
Por favor efetuar a alteração na linha 876, pois a chamada esta errada
Alteração da linha 876
$heigthText = $this->pTextBox($x, $y, $w, $hLinha, $texto, $aFontTit, 'C', 'C', 0, '', false);
Para:
$heigthText = $this->pdf->textBox($x, $y, $w, $hLinha, $texto, $aFontTit, 'C', 'C', 0, '', false);

Alteração da chamada da pTextBox na linha 876

---

src/CTe/Dacte.php

Corrigido o tratamento no método modalAquaviario em Dacte quando a tag 'infUnidCarga' retorna null. Atualmente é testado se o objeto é null e não o valor, sendo assim retorna um erro.

Cte com Modal = Aquaviário

---

src/NFe/Danfe.php

existe o parâmetro que dá opção de escolher se desejamos que apareçam os impostos na descrição do produto ou não
mas ele não permite que seja alterado externamente, acaba que não está sendo possivel escolher.
se ele for publico, podemos configurar como quisermos.

Não mostrar impostos na descrição dos produtos

---

src/CTe/Daevento.php
src/NFe/Danfe.php

Fix do erro: "Call to a member function getElementsByTagName() on null => line 3305" quando é gerado a pré-visualização de uma NFe (de devolução) sem prótocolo.

Fix da NFe sem protocolo

---

src/NFe/Danfe.php

Habilitar Impressão da IM, para casos em que a cidade não tenha Nota Conjugada.

Impressão Inscrição Municipal

---

README.md

Arquivo DANFE foi movido para a pasta DOCS e não atualizado
Alteração ocorreu no commit e753af89b11e49461ac2fca024c2a7a235682262 de 05/Maio/2017

Link quebrado

---

src/CTe/Dacte.php

Método pSimpleGetDate foi renomeado por getTagDate
em commits anteriores deste repo, mas não havia sido
atualizado na classe Dacte

fix: Dacte chamava método inexistente

---

src/NFe/Danfe.php

No estado do RS o campo "xMsg" é opcional e dá erro na linha 3328 devido a não existir nenhuma mensagem no XML.
Para solucionar adicionei um "length" na linha 3327 que fará a verificação se existem algum item dentro antes.

Correção Danfe.php

---

src/NFe/Danfce.php

Removido a linha 320 ( $yImg = $margemInterna + $nImgH/2; ), pois estava recalculando a posição da imagem, com isso fazendo ela ser impressa no final da espaço em branco, sobrepondo a mensagem "Documento auxiliar....."

Variavel duplicada

---

src/NFe/Danfe.php

Quando não há valor para algumas colunas dos itens no DANFe, está sendo formatado como '0, 00' (com um espaço entre o separador e os decimais). Este formato de números é incorreto

Ajuste formato dos impostos quando zerados.

---

src/CTe/Dacte.php
src/MDFe/Damdfe.php

Quando modal não for do tipo aquaviário a tag **detCont** não existe no xml.
Sugestão de aumento da autura da caixa de texto.
Quando na observação contém muita informação a impressão fica cortada, conforme imagem abaixo:

Correção modal, aumento da caixa de texto das observações

---

src/CTe/Dacte.php
src/CTe/DacteOS.php
src/Common/DaCommon.php
src/MDFe/Damdfe.php
src/NFe/Danfce.php
src/NFe/Danfe.php

Alteração simples para suportar uma sinalização externa de cancelamento nos documentos. Útil para trabalhar com arquivos XML que não seguem o padrão adotado pela biblioteca de atualizar o XML original com o protocolo de cancelamento. Tem relação com #374 
Não altera nenhuma regra e tem a mesma prioridade que o protocolo de cancelamento para impressão da marca d'agua.
Estou aberto a sugestões e posso alterar a implementação conforme desejarem.

Adiciona flag externa de cancelamento

---

src/NFe/Danfe.php

Em alguns casos, na última página, as descrições dos últimos itens ultrapassavam o limite vertical da linha que delimita o fim do documento. Foi ajustada a largura dos campos "DESCRIÇÃO DO PRODUTO / SERVIÇO" e "QUANT" de forma que uma maior descrição possa caber adequadamente na renderização do espaço disponível para cada linha sem que o restante do documento sofra algum efeito colateral.
Signed-off-by: Victor Hugo Diniz Brito dos Santos <victor.diniz.ti@gmail.com>

Correção de sobreposição de descrição do item na última página

---

src/CTe/Dacte.php

A tag de documento anterior não era carregada, e o nome da tag que contem a chave de CTe estava incorreta.

Correçao para impressao das chaves de CTe vinculada em documentos transp. anterior

---

src/NFe/Traits/TraitBlocoVII.php

Ajuste para altura do bloco se o xml possuir a tag xMsg.
Teste com CPF
Teste sem CPF

Ajuste altura bloco VII

---

examples/nfe/danfesimples.php
src/NFe/DanfeSimples.php

-Modificado para suportar a geração de DANFe simplificado para etiqueta térmica 100x150, que é padrão no e-commerce.

Adição de DANFe Simplificado para Etiqueta 100x150mm

---

src/NFe/DanfeSimples.php

Corrigido o texto NUMERL para NUMERO no Danfe Simplificado.
Adicionado linha contendo Município, UF e CEP do Emitente, pois é solicitado na NT.

Correções em Danfe Simplificado

---

src/Common/DaCommon.php

Se o atributo logomarca já foi inicializado (principalmente pelo metodo $danfe->logoParameters($logo, 'C', false);)
O método adjustImage não retornará null quando for chamado pelo método $danfe->render();

Verificar se já existe logomarca. Se sim, não retornar null no método adjustImage

---

src/NFe/Danfe.php

Alterando o Label que exibe CSOSN ou CST na listagem de produtos. 
O correto é exibir o CSOSN apenas quando o CRT for igual a 1, nos demais casos, deverá ser exibido CST.

Label CSOSN ou CST exibindo incorretamente para CRT = 2

---

src/NFe/Danfce.php
src/NFe/Traits/TraitBlocoIV.php

Inclusão da impressão do valor do frete conforme manual de orientação. O frete é necessário para NFC-e com entrega à domicílio.

Inclusão do valor do frete na DANFC-e

---

src/NFe/Danfe.php

Correção: datas de validade e fabricação dos lotes estavam formatando duas vezes gerando erro que impedia a exibição da Danfe
Novo parâmetro: $ocultarUnidadeTributavel
Novo método boleano: setOcultarUnidadeTributavel

Correção e novo parâmetro para uTrib

---

src/NFe/Danfe.php

Comando `echo` indevido na geração do DANFe estava causando problemas ao gerar o documento e devolver em uma requisição, pois adiciona este conteúdo ao corpo da resposta.

Remove echo indevido

---

src/Legacy/Dom.php

Vasculhei pelo projeto e parece que o método **loadXMLFile** não faz referência em nenhum local, assim como **NFePHP\DA\Legacy\FilesFolders** não existe mais.

Removendo loadXMLFile

---

src/MDFe/Damdfe.php

Adicionado a impressao do RNTRC do emitente no cabecalho do DAMDFe conforme manual, e corrigido a impressao da sigla 'IE' no cabecalho que nao era impressa devido a falta de parenteses no ternario.

Impressao do RNTRC do emitente no cabecalho do DAMDFe e correcao sigla de IE

---

src/NFe/Danfe.php

Alguns clientes tem problemas com o danfe, pois no danfe aparece escrito renavam e mostra o codigo do modelo (veicProd > cMod) do veículo, e alguns compradores não aceitam o carro pois no danfe esta um código do renavam e no documento do veiculo outro.

[UPD] cMod mostrando no danfe como renavam

---

src/NFe/Danfe.php

Os dados (chassi, cor, cilindrada...) estavam sobrepondo os itens.
Atual:
Alteração:
Desde já agradeço a atenção.
Cordialmente,

Ajusta exibição dos itens descritivos do veículo

---

src/NFe/DanfeSimples.php

Segue uma lista de correções:
* Gerar o Danfe simples mesmo sem as tags de transportadora. Refere-se a issue #477 .
* Se o volume nāo estiver presente no XML, omitir célula correspondente
* Se o volume estiver presente mas sem as informaçōes de peso, soma-se zero.
* Se informações adicionais nāo estiverem presentes, nāo monta a célula correspondente.

Proteções e melhorias na geraçāo do Danfe Simples

---

src/NFe/Danfe.php

Limita a 4 box por linha, aumenta horizontalmente a box, diminui a descrição das formas 18 e 19.

Ajusta box e descrição das Formas de pagamento

---

src/NFe/Traits/TraitBlocoVII.php

Quando uma nota é emitida em contingência off-line, ela deve ser transmitida o mais rapido possível, mas mesmo depois de transmitida e com numero de protocolo ela mostra "Pendente Autorização", com essa alteração agora vai mostrar o numero de Protocolo e Data que foi autorizada.

Fix: Mostrar Protocolo e Data Autorização quando transmitida

---

src/CTe/Dacte.php
src/CTe/DacteOS.php

Erro ao instanciar data de emissão e protocolo no Dacte/DacteOS devido ao timezone.
Poderíamos setar o timezone antes da geração do documento. Porém, percebi que na geração do documento auxiliar da NF-e se resolveu também desta forma. ex: [NFe/Danfe.php](https://github.com/nfephp-org/sped-da/blob/4fe72ce9628f87a2ee5530e29bc56e6e854c5dc6/src/NFe/Danfe.php#L910)

Fix: timezone Dacte e DacteOS

---

src/CTe/Dacte.php

Corrige máscara de celulares: 
De (xx9) 9999-8888 para (xx) 99999-8888

fix(dacte): corrige mascara de telefone celulares

---

src/NFe/DanfeSimples.php

Quando a NFe tinha modFrete !=9, porém sem a tag da transportadora (transporta) preenchida, o script travava ao tentar acessar a tag inexistente para montar o quadro de transporte. Adicionei uma condição a mais para que isso não aconteça.

Correção em DanfeSimples - Erro no campo de transporte

---

src/NFe/DanfeSimples.php

Correção do erro: Declaration of NFePHP\DA\NFe\DanfeSimples::monta() should be compatible with NFePHP\DA\Common\DaCommon::monta($logo = NULL)

Correção em monta()

---

src/NFe/Danfe.php

Realocado o if ($pag != $totpag) (linha 3088 no original) que impossibilitava a verificação da quantidade dos itens na última página do Danfe gerado, resultando em um erro de formatação. Agora ele verifica se existem itens de sobra e se é a última página, caso ambos os casos ocorram é incrementada mais uma página ao Danfe com os itens são adicionados. Caso precisem entrar em contato para analisar a alteração, meu e-mail é: [andersonjrignacio@gmail.com](mailto:andersonjrignacio@gmail.com). Obrigado desde já.

Danfe.php com erro de formatação

---

examples/nfe/danfe.php
src/NFe/Danfe.php

Flag para mostrar o número do item do pedido de compra na descrição do produto.

Flag para exibir o nº do item no pedido de compra

---

src/NFe/Danfe.php

Adicionado válidação para evitar que o processo quebre caso receba algum valor inválido.
Foi usado **ltrim** para remover os 0 a esquerda caso exista e encontrar os index do array e usado operador condicional **??** para válidar se existe de fato para não causar erro de **undefined index**.

Remove 0 a esquerda e válida se o index existe.

---

src/NFe/Danfe.php

O operador ternário não funciona se não tiver os parênteses por causa da concatenação de string.

Adicionado parênteses no operador ternário condicional.

---

src/NFe/Danfe.php

Parâmetro do controle se deve concatenar automaticamente informações sobre rastro e medicamento na descrição do produto, como por exemplo, lote, validade, fabricacão.

Exibe/Oculta informações de Rastro e Medicamento

---

src/Legacy/Pdf.php
src/NFe/Danfe.php

Essa PR visa corrigir os avisos de DEPRECATED encontrados na versão 8.2 do PHP, impedindo a a geração do PDF
> `Deprecated: Function utf8_decode() is deprecated`
> `Deprecated: Creation of dynamic property NFePHP\DA\NFe\Danfe::$nfeProc is deprecated`
> `Deprecated: Creation of dynamic property NFePHP\DA\NFe\Danfe::$detPag is deprecated`

Correções de compatibilidade com PHP 8.2

---

src/Legacy/Pdf.php

Correção para a exceção gerada no PHP 8.2 - Creation of dynamic property NFePHP\DA\Legacy\Pdf::$angle is deprecated

suporte a php 8.2

---

src/Legacy/FPDF/Fpdf181.php

Estou migrando o sistema aqui da empresa para PHP 8.x e me deparei com esse erro:
```
Warning: Use of undefined constant FPDF_FONTPATH - assumed 'FPDF_FONTPATH' 
(this will throw an Error in a future version of PHP) 
in /var/www/vendor/nfephp-org/sped-da/src/Legacy/FPDF/Fpdf181.php:100
```
Fiz uma correção simples para resolver o problema.

Corrigindo erro constante php usando self::

---

src/Legacy/Pdf.php

Baseada na documentação do método `mb_convert_encoding` https://www.php.net/manual/en/function.mb-convert-encoding.php se o terceiro parametro for omitido será utilizada `mbstring.internal_encoding setting` e no meu caso não posso definir ela para UTF-8 pois meu sistema está todo encodificado para ISO-8859-1. Nesse caso passei um array com dois prováveis encodings para que ele possa fazer a conversão corretamente.
Caso exista outro solução melhor ou se isso for impactar outros lugares aceito sugestões, para mim resolveu.

🌐 Corrigindo erros de encoding

---

src/NFe/DanfeSimples.php

- Evitando erros PHP 8.x quando não tem todas informações como: IE, Transportadora, Volumes, etc.
- Convertendo os caracteres para ISO-8859-1 para evitar erros de encoding.

✨ Melhorias danfe simples

---

src/NFe/Danfe.php

Não está sendo exibido o motivo de Danfe com status Denegada, e essa informação tem muito valor para o cliente.
Em uma versão mais antiga que estávamos usando, essa informação existia conforme a print abaixo:

Exibir motivo como submessage para status Denegada em  Danfe

---

src/MDFe/Damdfe.php

Desencadeava erro caso o XML não possuísse a tag infANTT.

Fix: Erro na geração do PDF

---

src/NFe/Danfe.php

Adicionando código de regime tributário (4) - Simples Nacional - Microempreendedor Individual MEI, conforme a versão 1.10 da Nota Técnica 2024.001, publicada pela Sefaz.
**Documentos base**
- https://noticias.iob.com.br/nota-fiscal-mei-crt/
- [NT2024.001-CRT-MEI.pdf](https://github.com/user-attachments/files/17382687/NT2024.001-CRT-MEI.pdf)

feat: adicionando código de regime tributário 4 - Simples Nacional - Microempreendedor Individual MEI

---

src/NFe/Danfe.php

Altera a descrição da forma 05 Cartão da loja adicionando "Outros Crediários" para ficar compatível com o passado e também com a planilha da SEFAZ:
Cartão da Loja (Private Label), Crediário Digital, Outros Crediários 	 Descrição:
"Cartão da loja (na forma de crediário), Crediário Digital, Crediário com ou sem Carnê etc.  Não usar para o cartão de loja ""bandeirado""."
[Tabela de Meios de Pagamento - Vigente a partir de 01/07/2024 - Publicada em 07/06/2024](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=nB7L5ty6geI=)
Tabela dos códigos de meios de pagamento
[Tabela_de_meios_de_pagamento - 03062024.xlsx](https://github.com/user-attachments/files/16097763/Tabela_de_meios_de_pagamento.-.03062024.xlsx)

Altera a descrição da forma 05 Cartão da loja adicionando "Outros Crediários"

---

src/NFe/DanfeEtiqueta.php

Na nova nota técnica deixou de ser obrigatório o valor total da NFe no DANFe Etiqueta.

Remoção do valor total da NFe do DanfeEtiqueta. NT 2020.004 - v1.10

---

src/MDFe/Damdfe.php

Adicionada uma verificação adicional para garantir que a tag infANTT esteja definida antes de tentar acessar RNTRC. Verificado se RNTRC está presente dentro de infANTT antes de acessar seu valor, prevenindo assim a exceção.

Corrige validação ao gerar MDF-e quando RNTRC não é obrigatório #576

---

src/Legacy/Common.php

Adicionadas flags padrão do PHP 8.1 na chamada da função html_entity_decode, pois a mesma não converte as entidades HTML corretamente quando utilizada no PHP 7.4.x

Ajustes entidades HTML - PHP 7.4.x

---

src/Common/DaCommon.php

o erro que está acontecendo é:
[2025-07-16 09:22:42] production.ERROR: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile {"exception":"[object] (ErrorException(code: 0): imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile at /var/www/html/vendor/nfephp-org/sped-da/src/Common/DaCommon.php:303)
Este warning ocorre porque o libpng (a partir da versão 1.6) valida de forma mais rígida o chunk de perfil de cor iCCP nos arquivos PNG e emite o aviso quando encontra um perfil sRGB incorreto ou malformado 
Para muitos usuários, a solução simples é remover esse chunk inválido usando ferramentas como ImageMagick ou pngcrush (ou seja, teria que passar a imagem por um editor para reconfigurar o arquivo mas o arquivo funciona, abre, porem nao …

Corrige um erro específico de algumas versões de php

---

src/NFe/Danfe.php

Aqui em MG é obrigatório exibir no DANFE os dados do ST retido na Compra.

Volta com dados de impostos na descrição do produto
